stages:
  - build
  - deploy

variables:
  AZURE_WEBAPP_NAME: "CmvConstructions" # Replace with your Azure App Service name
  AZURE_APP_SERVICE: "ASP-CMVConstrutions-ade0" # Optional, depends on your setup
  AZURE_RESOURCE_GROUP: "CMVConstrutions"
  AZURE_REGION: "West US"

build:
  stage: build
  script:
    - dotnet restore
    - dotnet publish -c Release -o publish

deploy:
  stage: deploy
  script:
    - |
      az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src-path publish
